### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by NathanBnm**
+ Minor improvements for translations

### CODE REVIEW

**Comment by casasfernando** [comment]
Thanks for your contribution to the project Nathan.
I reviewed the PR, and for the most part it looks good to me.
I have some doubts about the proposed changes to Indicator.vala and PopoverWidget.vala.

- Indicator.vala: Do we really need those? Did you test that with the changes notifications text is working as expected?
- PopoverWidget.vala: Do we really need this change?

Looking forward your feedback.

**Comment by NathanBnm** [comment]
Hi @casasfernando!

> Indicator.vala: Do we really need those? Did you test that with the changes notifications text is working as expected?

I was not able to test the notifications because I have no AirPods :smile: However this should not cause any issue but maybe you can try on your side by building the app from my branch?

When there is a text concatenation like in your case you have to put a variable using the `printf` method because the order of words differs depending of the languages. Here it's the case in French: "100% charged" becomes "Chargé à 100%" after translation. Adding variables also adds more context for translators and avoids translation errors

> PopoverWidget.vala: Do we really need this change?

Yes it's better to use the ellipsis symbol rather than the three dots. You can read more about this in [the elementary OS Human Interface Guideline](https://docs.elementary.io/hig/reference/text#using-ellipses)

**Comment by casasfernando** [comment]
Since I've commited the improvements you suggested for the meson build system and a couple of other things, I will look into merging this one manually since there are some conflicts and unneeded changes now.

Thanks.

**Comment by NathanBnm** [comment]
@casasfernando I can fix the conflicts

**Comment by casasfernando** [comment]
No worries, I'm pretty much done and will commit it in a few minutes.

**Comment by casasfernando** [comment]
It's done.

Thanks a lot for your contribution @NathanBnm!

Closing PR.

**Pull request closed without merging**
